name: Lint
on:
  pull_request:
    branches: [main]

jobs:
  Lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log
